### ISSUE TITLE
Failed to render dpp list with no subscription

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#475]
### What happened?

With the response to `dataplane+insights`:

```json
{
 "total": 1,
 "items": [
  {
   "type": "DataplaneOverview",
   "mesh": "default",
   "name": "redis-1",
   "creationTime": "2022-11-30T11:27:36.245951+01:00",
   "modificationTime": "2022-11-30T11:27:36.245951+01:00",
   "dataplane": {
    "networking": {
     "address": "192.168.0.1",
     "inbound": [
      {
       "port": 9000,
       "servicePort": 6379,
       "tags": {
        "kuma.io/service": "redis"
       }
      }
     ]
    }
   }
  }
 ],
 "next": null
}
```

I get:

```
index.c8163df9.js:1 TypeError: Cannot read properties of undefined (reading 'subscriptions')
    at Fee (index.c8163df9.js:30:15896)
    at yd.fn (DataPlaneListView.89096fce.js:1:2908)
    at yd.run (index.c8163df9.js:1:6278)
    at get value [as value] (index.c8163df9.js:1:14369)
    at ie (index.c8163df9.js:1:13446)
    at Proxy.<anonymous> (DataPlaneListView.89096fce.js:1:4055)
    at ic (index.c8163df9.js:1:17784)
    at yd.Y [as fn] (index.c8163df9.js:1:41522)
    at yd.run (index.c8163df9.js:1:6278)
    at b.update (index.c8163df9.js:1:41803)
```

We wrongly assume there's always a subscription which is not the case if no dpp was ever started

**Comment by kleinfreund** [comment]
So the entire `dataplaneInsight` object can be absent in this response? 😞

**Comment by lahabana** [comment]
> So the entire dataplaneInsight object can be absent in this response? 😞

Yes if the dp was never connected
